package ultrasound

import chisel3._
import chiseltest._
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.matchers.should.Matchers
import java.nio.file.{Files, Paths}
import java.nio.ByteOrder

/**
  * Loopback test: verifies that PC-generated BRAM binary files
  * produce correct frame bitmaps when fed through BramReader -> DataMapper.
  *
  * These tests read actual BRAM .bin files from host/loopback_output/
  * (generated by host/tests/end_to_end_loopback.py) and confirm that
  * the FPGA-side reconstruction matches the PC-side LUT expectations.
  */
class BramFileLoopbackSpec extends AnyFlatSpec with ChiselScalatestTester with Matchers {

    val div = 30
    val phaseDutyBits = 5
    val lut = LutGenerator.generateLut(div, phaseDutyBits)

    /** Helper: read a little-endian uint32 BRAM binary file. */
    def readBramFile(path: String): Array[BigInt] = {
        val bytes = Files.readAllBytes(Paths.get(path))
        require(bytes.length == 64 * 4, s"Expected 256 bytes (64 uint32), got ${bytes.length}")
        val bb = java.nio.ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        Array.fill(64) { BigInt(bb.getInt() & 0xFFFFFFFFL) }
    }

    /** Top-level integration module for loopback test. */
    class LoopbackTop extends Module {
        val io = IO(new Bundle {
            val cycleStart = Input(Bool())
            val bramAddr   = Output(UInt(6.W))
            val bramRen    = Output(Bool())
            val bramData   = Input(UInt(32.W))
            val valid      = Output(Bool())
            val cycleMatch = Output(Bool())
            val frameData  = Output(Vec(64, UInt(div.W)))
            val ready      = Output(Bool())
        })

        val bramReader = Module(new BramReader(64))
        val dataMapper = Module(new DataMapper(div, phaseDutyBits))

        bramReader.io.cycleStart := io.cycleStart
        io.bramAddr := bramReader.io.bramAddr
        io.bramRen  := bramReader.io.bramRen
        bramReader.io.bramData := io.bramData

        dataMapper.io.rawData := bramReader.io.rawData
        dataMapper.io.valid   := bramReader.io.valid

        io.valid      := bramReader.io.valid
        io.cycleMatch := bramReader.io.cycleMatch
        io.frameData  := dataMapper.io.frameData
        io.ready      := dataMapper.io.ready
    }

    def runLoopbackTest(testName: String, bramFile: String): Unit = {
        it should s"produce correct frame bitmaps for $testName" in {
            val rows = readBramFile(bramFile)

            test(new LoopbackTop) { dut =>
                // Trigger a cycle read
                dut.io.cycleStart.poke(true.B)
                dut.io.bramData.poke(0.U)
                dut.clock.step()
                dut.io.cycleStart.poke(false.B)

                // Feed 64 rows of BRAM data with 1-cycle read latency
                for (addr <- 0 until 64) {
                    dut.io.bramAddr.expect(addr.U)
                    dut.io.bramRen.expect(true.B)
                    dut.io.bramData.poke(rows(addr).U(32.W))
                    dut.clock.step()
                }

                // Wait for sCheck -> sDone
                while (!dut.io.valid.peekBoolean()) { dut.clock.step() }

                dut.io.valid.expect(true.B)
                dut.io.cycleMatch.expect(true.B)
                dut.io.ready.expect(true.B)

                // Verify each transducer's frame bitmap against LUT expectation
                for (i <- 0 until 64) {
                    val duty  = (rows(i) >> 8) & 0x1F
                    val phase = rows(i) & 0x1F
                    val expectedBitmap = lut(duty.toInt)(phase.toInt)
                    val actual = dut.io.frameData(i).peekInt()
                    actual shouldBe expectedBitmap
                }
            }
        }
    }

    // ------------------------------------------------------------------
    // Test cases generated by host/tests/end_to_end_loopback.py
    // ------------------------------------------------------------------
    val outputDir = "host/loopback_output"

    val testCases = Seq(
        "unet_1focus_center",
        "unet_1focus_offset",
        "unet_2foci",
        "unet_3foci",
        "gspat_1focus",
        "gspat_2foci",
    )

    for (name <- testCases) {
        val filePath = s"$outputDir/${name}_bram.bin"
        if (Files.exists(Paths.get(filePath))) {
            runLoopbackTest(name, filePath)
        } else {
            // Register a pending/skip test so sbt doesn't silently ignore
            it should s"find BRAM file for $name" in {
                pending
            }
        }
    }
}
